name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
        
      - name: Build for Steam Version
        run: dotnet publish -c Steam -p:CI="${{ github.run_number }}"

      - name: Upload Artifact for Steam Version
        uses: actions/upload-artifact@v4
        with:
          name: SNTools-Steam
          path: "bin/SNTools Steam.exe"
        
      - name: Build for GDK Version
        run: dotnet publish -c GDK -p:CI="${{ github.run_number }}"

      - name: Upload Artifact for GDK Version
        uses: actions/upload-artifact@v4
        with:
          name: SNTools-GDK
          path: "bin/SNTools GDK.exe"